---
title: "Data compiler - annual averages"
author: "Tanya Rogers"
date: "10/27/2021"
output: html_document
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = 'docs',
      knit_root_dir = '../..',
      envir = globalenv()
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This combines the various csv files into `annual_data_compiled.csv`, and makes some plots of the time series.

```{r, message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
flow=read.csv("data/annual_averages/annual_average_deltawide_flow.csv")
nutwq=read.csv("data/annual_averages/emp_waterquality_mean.csv")
benthic=read.csv("data/annual_averages/benthic.csv")
fishbm=read.csv("data/annual_averages/fish_FMWT.csv")
zoop=read.csv("data/annual_averages/zoop.csv")

zoopbm=select(zoop, Year, grep("BPUE", colnames(zoop)))

combined=flow %>% 
  rename(Year=Calendar_Year) %>% select(-Water_year) %>% 
  full_join(nutwq, by="Year") %>% 
  full_join(benthic, by = c("Year"="year")) %>%
  #full_join(fishab, by="Year") %>% 
  full_join(fishbm, by="Year") %>% 
  full_join(zoopbm, by="Year") %>% 
  arrange(Year)

write.csv(combined, "data/annual_averages/annual_data_compiled.csv", row.names = F)
```

Plots

```{r, fig.width=8, fig.height=20}
datalong=gather(combined,Var,Value,2:ncol(combined))
datalong$Var=factor(datalong$Var,levels = unique(datalong$Var))

ggplot(datalong, aes(y=Value, x=Year)) +
  facet_wrap(.~Var, scales = "free_y", ncol = 2) +
  geom_line() + geom_point() +
  theme_bw()
```
