---
title: "Amphipod biomass conversions"
author: "Sarah Perry"
output: html_document
editor_options: 
  chunk_output_type: console
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = 'docs',
      knit_root_dir = "../",
      envir = globalenv()
    )
    })
---


```{r}
library(tidyverse)
library(lubridate)
`%notin%` <- Negate(`%in%`)
```

```{r}
df_codes <- read_csv('data/data_in/MysidAmphipodSpeciesLookUp.csv')
df_data <- read_csv('data/data_in/EMP_MysidAmphipodLengths.csv')
df_biomass <- read_csv('data/data_in/Biomass conversions.csv')

# filter to species needed
# Aab = Ampelisca abdita, Gd = Gammarus, Asp & Ast = americorophium, Cra = Crangonyx, Hya = Hyalella
# Cor = sinocorophium, UnidC = monocorophium
species_list <- c('Aab','Gd','Asp','Ast','Cra','Hya','Cor','UnidC','Gja')
df_data <- df_data %>% filter(SpeciesCode %in% species_list)

# filter by date >= 2014
df_data <- df_data %>% 
  mutate(SampleDate=as.Date(SampleDate, format = '%m/%d/%Y'))%>%
  filter(year(SampleDate) >= 2014)

# add in species code
df_data <- right_join(df_data, df_codes[1:2], by = 'SpeciesCode')

# equation
lw_conversion <- function(len, a, b){
  weight <- a*(len^b)
  return(weight)
}

df_data <- df_data %>%
  mutate(
    SpeciesName =
      case_when(
        SpeciesCode %notin% c('Cor','UnidC') ~ SpeciesName,
        SpeciesCode == 'Cor' ~ 'Sinocorophium sp.',
        SpeciesCode == 'UnidC' ~ 'Monocorophium sp.')
  )

df_codes <- df_codes %>%
  mutate(
    SpeciesName =
      case_when(
        SpeciesCode %notin% c('Cor','UnidC') ~ SpeciesName,
        SpeciesCode == 'Cor' ~ 'Sinocorophium sp.',
        SpeciesCode == 'UnidC' ~ 'Monocorophium sp.')
  )
```

```{r}
# rename biomass species to be consistent
df_biomass <- df_biomass %>% rename(SpeciesName = Taxname)

df_biomass <- df_biomass %>%
  mutate(
    SpeciesName =
      case_when(
        SpeciesName %notin% c('Hyalella','Crangonyx','Sinocorophium alienense','Monocorophium') ~ SpeciesName,
        SpeciesName == 'Hyalella' ~ 'Hyalella sp.',
        SpeciesName == 'Crangonyx' ~ 'Crangonyx sp.',
        SpeciesName == 'Sinocorophium alienense' ~ 'Sinocorophium sp.',
        SpeciesName == 'Monocorophium' ~ 'Monocorophium sp.'
        )
    )

# filter conversions by species, check preservative
df_biomass <- right_join(df_biomass, df_codes[1:2], by = 'SpeciesName')
df_biomass <- df_biomass %>% filter(SpeciesCode %in% species_list)

# Asp, Ast, and Gd have ethanol and formalin, so remove ethanol
df_biomass$label <- paste(df_biomass$SpeciesCode, df_biomass$Preservative)

df_biomass <- df_biomass %>%
  filter(df_biomass$label %notin% c('Asp Ethanol','Ast Ethanol','Gd Ethanol')) %>%
  subset(select = -c(label))

# filter to just code, a, and b after fixing up code names
df_biomass <- df_biomass %>% subset(select = c('SpeciesCode','a','b'))

# join data
df_data <- right_join(df_data, df_biomass, by = 'SpeciesCode')
```

```{r}
# convert 
df_data_sum <- df_data %>%
  mutate(Biomass = lw_conversion(Size, a, b), 
         Biomass = Biomass*1000*0.2*0.4, # Convert to micrograms (*1000), then to dry weight (*0.2), then to carbon weight (*0.4)
         Month=month(SampleDate),
         SpeciesName=word(SpeciesName, 1))%>% # Just keep the genus names for adding to biomass
  group_by(SpeciesName, Month)%>%
  summarise(Biomass_mean=mean(Biomass), Biomass_sd=sd(Biomass), N=n(), .groups="drop")

# export
write_csv(df_data_sum, 'data/data_in/amphipod_biomass_conversions.csv')
```

Plot biomass conversions
```{r}
ggplot(df_data_sum, aes(x=SpeciesName, y=Biomass_mean, ymin=Biomass_mean-Biomass_sd, ymax=Biomass_mean+Biomass_sd))+
  geom_pointrange()+
  facet_wrap(~Month)+
  ylab("Mean monthly biomass (ug)")+
  theme_bw()+
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

Plot sample size
```{r}
ggplot(df_data_sum, aes(x=SpeciesName, y=N))+
    geom_point()+
    facet_wrap(~Month)+
    theme_bw()+
    theme(axis.text.x=element_text(angle=45, hjust=1))
```

