---
title: "Nutrient Data - Yearly"
output:
  html_document:
    code_folding: hide
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = 'docs',
      knit_root_dir = "../",
      envir = globalenv()
    )
    })
---

```{r imports, echo = FALSE, results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(ggmap)
library(lubridate)
library(discretewq)
# source('../functions/nutrient_funcs.R', local = TRUE)
# source('../functions/region_assigner.R', local = TRUE)
source('functions/region_assigner.R')
source('functions/nutrient_funcs.R')
if(utils::packageVersion('discretewq') < '2.1.0') {
    stop('discretewq version >= 2.1.0 is required, please update discretewq.')
    # https://github.com/sbashevkin/discretewq/
}
```

```{r read-in-data, warning = FALSE, message = FALSE}
# read in data
df_wq <- read_wq_data(monthly = FALSE)

df_wq$DissAmmonia <- replace_rl(df_wq, 'DissAmmonia')
df_wq$DissNitrateNitrite <- replace_rl(df_wq, 'DissNitrateNitrite')
df_wq$DissOrthophos <- replace_rl(df_wq, 'DissOrthophos')

df_wq <- clean_df(df_wq)
```

# Check Temporal Coverage
```{r check-temporal-coverage, fig.width=15, fig.height=8}
# check temporal coverage
plt <- check_temporal_coverage(df_wq)

plt
```

Core stations are:

* P8
* MD10A
* D8
* D7
* D6
* D41
* D4
* D28A
* D26
* C3/C3A?
* C10/C10A?

(D10, D12, D16, D22 are missing decades of nutrient data)

# Subset out Relevant Stations
```{r subset-relevant-stations}
# subset stations
station_list <- c('P8','MD10A','D8','D7','D6','D41','D4','D28A','D26','C3','C3A','C10','C10A')
df_wq <- df_wq[df_wq$Station %in% station_list,]

# check temporal coverage
plt <- check_temporal_coverage(df_wq)
plt
```

# Check Spatial Coverage
```{r check-spatial-coverage, results='hide', message=FALSE, warning = FALSE, results = 'hide'}
map <- create_station_map(df_wq)
map
```

# Check if C3/C3A and C10/C10A can be combined {.tabset .tabset-pills}
```{r, results='asis'}
analytes <- unique(df_wq$Analyte)
stations_list <- list(c('C10','C10A'),c('C3','C3A'))

for (stations in stations_list){
  cat('\n##', stations, '{.tabset .tabset-fade .tabset-pills}')
  for (analyte in analytes){
    cat('\n###', analyte, '\n')
    df_check <- df_wq %>% filter(Station %in% stations, Analyte == analyte)
    plt <- ggplot(df_check) +
      geom_line(aes(Date, Value, color = Station)) +
      ylab(analyte)
  
    plot(plt)
    cat('\n')
  }
}
```

#
Looks good to me, so will combine the stations.
```{r final-temporal-check}
df_wq <- combine_wq_stations(df_wq)

# check temporal coverage
plt <- check_temporal_coverage(df_wq)
plt
```

```{r check-scatter-plots, fig.width=15, fig.height=8}
df_wq <- subset(df_wq, !(Analyte == 'DissOrthophos' & df_wq$Value > 4))
df_wq <- subset(df_wq, !(Analyte == 'DissNitrateNitrite' & df_wq$Value > 10))

ggplot(data=df_wq, aes(Date, Value, color = Station)) +
	geom_point() +
	facet_wrap( ~ Analyte, ncol = 2, scales='free_y')
```

```{r assign regions}
df_wq <- df_wq %>%
region_assigner(analysis='annual')
```

```{r create-stations-df}
df_stations <- subset(df_wq, select = c(Station, Latitude, Longitude))
df_stations <- distinct(df_stations)

# subset out coords for merged stations
df_stations <- df_stations[!(df_stations$Latitude %in% c(38.04381, 37.67575, 38.34575)),]
```

```{r flip-wide, message=FALSE, warning = FALSE, results = 'hide'}
df_wq$Year <- lubridate::year(df_wq$Date)
df_wq$Month <- lubridate::month(df_wq$Date)

# average by region
df_wq$Value <- round(df_wq$Value, 3)

df_wq_regions <- df_wq %>%
  group_by(Year, Region, Analyte) %>%
  summarize(Value = mean(Value), .groups = 'drop')

df_wq_noregions <- df_wq %>%
  group_by(Year, Analyte) %>%
  summarize(Value = mean(Value), .groups = 'drop')


df_wq_wide_regions <- pivot_wider(data=df_wq_regions, id_cols=c(Year,Region),
                          names_from=Analyte, values_from=Value)

df_wq_wide_noregions <- pivot_wider(data=df_wq_noregions, id_cols=c(Year),
                          names_from=Analyte, values_from=Value)
```

```{r export}
write_csv(df_wq_wide_regions, 'data/annual_averages/nutrient_data_yearly_regions.csv')
write_csv(df_wq_wide_noregions, 'data/annual_averages/nutrient_data_yearly_noregions.csv')
write_csv(df_stations, 'data/stations/stations_nutrients_yearly.csv')
```
