---
title: "Temperature"
output: html_document
editor_options: 
  chunk_output_type: console
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = 'docs',
      knit_root_dir = "../",
      envir = globalenv()
    )
  })
---

```{r, message=FALSE}
library(sf)
library(stars)
library(dplyr)
library(ggplot2)
library(lubridate)
library(readr)
```

Load model-predicted temperature data
```{r}
temp_data<-readRDS("~/WQ-discrete/Temperature analysis/Discrete Temp Data.Rds")
temp_predictions<-readRDS("~/WQ-discrete/Temperature analysis/Model outputs and validations/newdata_all_sum.Rds")

Delta<-deltamapr::R_EDSM_Subregions_Mahardja%>%
  filter(SubRegion%in%unique(temp_data$SubRegion))%>% # Remove regions outside our domain of interest
  dplyr::select(SubRegion)

Data_effort <- temp_data%>%
  st_drop_geometry()%>%
  group_by(SubRegion, Month, Year)%>%
  summarise(N=n(), .groups="drop")%>%
  filter(Year>=1975)%>%
  group_by(Month, SubRegion)%>%
  summarise(n_years=n_distinct(Year), .groups="drop")%>%
  filter(n_years>=45)

temp_predictions_filtered <- temp_predictions%>%
  st_as_sf(coords=c("Longitude", "Latitude"), crs=4326)%>%
  st_transform(crs=st_crs(Delta))%>%
  st_join(Delta)%>%
  semi_join(Data_effort, by=c("SubRegion", "Month"))
```

Plot the regions included
```{r, fig.width=12, fig.height=12}
Temp_spatial_plot<-Delta%>%
  right_join(Data_effort, by="SubRegion")


ggplot()+
  geom_sf(data=deltamapr::WW_Delta%>%st_transform(crs=st_crs(Delta)))+
  geom_sf(data=Temp_spatial_plot, aes(fill=SubRegion), alpha=0.8)+
  facet_wrap(~month(Month, label=TRUE))+
  scale_fill_viridis_d(guide=guide_legend(direction = "horizontal", title.position = "top", ncol = 4))+
  coord_sf(crs = 4326)+
  theme_bw()+
  theme(legend.position = "bottom")
```

Select only the regions present in every month
```{r, fig.width=12, fig.height=12}
regions_all_months<-Data_effort%>%
  group_by(SubRegion)%>%
  summarise(n_months=n_distinct(Month))%>%
  filter(n_months==12)

Temp_spatial_month_plot<-Delta%>%
  right_join(regions_all_months, by="SubRegion")


ggplot()+
  geom_sf(data=deltamapr::WW_Delta%>%st_transform(crs=st_crs(Delta)))+
  geom_sf(data=Temp_spatial_month_plot, aes(fill=SubRegion), alpha=0.8)+
  scale_fill_viridis_d(guide=guide_legend(direction = "horizontal", title.position = "top", ncol = 4))+
  coord_sf(crs = 4326)+
  theme_bw()+
  theme(legend.position = "bottom")
```

Select only the regions present in every month excluding winter
```{r, fig.width=12, fig.height=12}
regions_most_months<-Data_effort%>%
  filter(!Month%in%c(12,1,2))%>%
  group_by(SubRegion)%>%
  summarise(n_months=n_distinct(Month))%>%
  filter(n_months==9)

Temp_spatial_most_month_plot<-Delta%>%
  right_join(regions_most_months, by="SubRegion")


ggplot()+
  geom_sf(data=deltamapr::WW_Delta%>%st_transform(crs=st_crs(Delta)))+
  geom_sf(data=Temp_spatial_most_month_plot, aes(fill=SubRegion), alpha=0.8)+
  scale_fill_viridis_d(guide=guide_legend(direction = "horizontal", title.position = "top", ncol = 4))+
  coord_sf(crs = 4326)+
  theme_bw()+
  theme(legend.position = "bottom")
```

Filter data to just regions present in all months (including winter), then calculate yearly averages
```{r}
temp_sum<-temp_predictions_filtered%>%
  st_drop_geometry()%>%
  filter(SubRegion%in%unique(regions_all_months$SubRegion))%>%
  group_by(Month, Year)%>%
  summarise(Temperature=mean(Monthly_mean), .groups="drop")%>%
  group_by(Year)%>%
  summarise(Temperature=mean(Temperature), .groups="drop")%>%
  filter(Year>=1975)

write_csv(temp_sum, "data/annual_averages/temperature.csv")
```

Plot Temperature timeseries
```{r}
ggplot(temp_sum, aes(x=Year, y=Temperature))+
  geom_point()+
  theme_bw()
```

