---
title: "zoop heatmap"
output: html_document
editor_options: 
  chunk_output_type: console
knit: (function(input, ...) {
    )
    rmarkdown::render(
      input,
      output_dir = 'docs',
      knit_root_dir = "../",
      envir = globalenv()
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages
```{r, message=FALSE}
require(dplyr)
require(zooper)
require(lubridate)
require(readr)
require(tidyr)
require(ggplot2)
require(readxl)
require(stringr)
require(sf)
```

Load core stations
```{r, message=FALSE}
download.file("https://portal.edirepository.org/nis/dataviewer?packageid=edi.522.7&entityid=71dd301f30a2bc2e40f5da573dde9f97", destfile = file.path(tempdir(), "zoop_station_lookup.csv"))

zoop_stations<-read_csv(file.path(tempdir(), "zoop_station_lookup.csv"))%>%
  filter(Core%in%c(1, 2))
```

Load zoop data
```{r}
zoop_data<-Zoopsynther(Data_type="Community", Sources="EMP", Time_consistency = TRUE)%>%
  filter(Station%in%zoop_stations$StationNZ)%>%
  mutate(Month=month(Date))
```

Summarize zoop effort by date and station
```{r}
zoop_data_station<-zoop_data%>%
  select(Month, Year, Station)%>%
  distinct()%>%
  mutate(type="present")%>%
  complete(Month, Year, Station, fill=list(type="missing"))%>%
  mutate(Date=dmy(paste("1", Month, Year)))
```

Plot zoop effort by date and station
```{r}
ggplot(zoop_data_station, aes(x=Date, y=Station, color=type))+
  geom_point()+
  scale_color_manual(values=c("firebrick3", "black"))+
  theme_bw()
```


Summarize zoop effort by month and year
```{r}
zoop_data_sum<-zoop_data%>%
  group_by(Month, Year)%>%
  summarise(N=n(), .groups="drop")
```

Plot heat map
```{r}
ggplot(zoop_data_sum, aes(y=Month, x=Year, fill=N))+
  geom_tile()+
  scale_fill_viridis_c()+
  scale_y_continuous(breaks=1:12)+
  coord_cartesian(expand=FALSE)+
  theme_bw()
```

Remove stations that aren't continuous
```{r}
zoop_data_continuous<-filter(zoop_data, !Station%in%c("NZEZ6", "NZEZ2", "NZD16", "NZD06", "NZ080", "NZ042"))

# Make sure the right number of stations was removed
length(setdiff(unique(zoop_data$Station), unique(zoop_data_continuous$Station)))==6
```

Plot the final set of stations
```{r}
ggplot()+
  geom_sf(data=deltamapr::WW_Delta%>%st_transform(crs=4326))+
  geom_point(data=zoop_data_continuous%>%select(Station, Latitude, Longitude)%>%distinct(), 
             aes(x=Longitude, y=Latitude),
             color="red")
```

Read in zoop mass conversions and groupings
```{r}
zoop_mass_group<-read_excel("data/data_in/Zoop Categories for SEM.xlsx", na = "NA")%>%
  mutate(Taxlifestage=paste(Taxname, Lifestage))%>%
  rename(Group=`SEM Category`)%>%
  mutate(Group=str_replace_all(Group, " ", "_"))

# List all the zoop groups
unique(zoop_mass_group$Group)
```

Load Mysid biomass data
```{r}
zoop_mysid<-read_excel("data/data_in/1972-2020MysidBPUEMatrix.xlsx",
                       sheet="Mysid_BPUE_matrix_1972-2020", na = "NA",
                       col_types = c(rep("numeric", 4), "date", "text", "text", rep("text", 7), rep("numeric", 8)))%>%
  select(Date=SampleDate, Station=StationNZ, `Acanthomysis aspera`:Unidentified)%>%
  mutate(BPUE_mysid=rowSums(select(., -Date, -Station), na.rm=T))%>%
  mutate(BPUE_mysid=BPUE_mysid*1000, # Convert to ug
         Group="Mysida")%>%
  mutate(SampleID=paste("EMP", Station, Date))%>%
  filter(Station%in%zoop_stations$StationNZ)%>%
  filter(!Station%in%c("NZEZ6", "NZEZ2", "NZD16", "NZD06", "NZ080", "NZ042"))%>%
  select(SampleID, Group, BPUE_mysid)
```


Start processing the zoop data
```{r}
zoop_data_mass<-zoop_data_continuous%>%
      filter(
        !(SizeClass=="Meso" & #eliminating species which are counted in meso and micro and retained better in the micro net from the meso calcs
            
            Taxlifestage%in%paste(c("Asplancha Adult", "Copepoda Larva","Cyclopoida Juvenile", "Eurytemora affinis Larva", "Harpacticoida Undifferentiated",
                                    "Keratella Adult", "Limnoithona Adult", "Limnoithona Juvenile", "Limnoithona sinenesis Adult", "Limnoithona tetraspina
                                    Adult", "Oithona Adult", "Oithona Juvenile", "Oithona davisae Adult", "Polyarthra Adult","Pseudodiaptomus Larva", 
                                    "Rotifera Adult", "Sinocalanus doerrii Larva", "Synchaeta Adult", "Synchaeta bicornis Adult", "Trichocerca Adult")))| 
            
          !(SizeClass=="Micro" & #removing categories better retained in meso net from micro net matrix
              
             Taxlifestage%in%paste(c("Cirripedia Larva", "Cyclopoida Adult", "Oithona similis"))) |
              
          Family=="Mysidae")%>%
      left_join(zoop_mass_group, by=c("Taxlifestage", "Lifestage", "Taxname"))%>%
      mutate(BPUE=CPUE*Carbon_mass_micrograms,
             Group=if_else(Family=="Mysidae", "Mysida", Group))%>%
  left_join(zoop_mysid, 
            by=c("Group", "SampleID"))%>%
  filter(!is.na(Group))%>% # This removes the group copepod nauplii
  mutate(BPUE=if_else(is.na(BPUE), BPUE_mysid, BPUE))%>%
      group_by(Year, Group)%>%
      summarise(across(c(BPUE, CPUE), ~sum(.x, na.rm=T)), .groups="drop")%>%
  pivot_wider(names_from = Group, values_from = c(BPUE, CPUE),
    names_glue = "{Group}_{.value}")

str(zoop_data_mass)

write_csv(zoop_data_mass, "data/annual_averages/zoop.csv")
```

