```{r}
library(tidyverse)
library(lubridate)
`%ni%` <- Negate(`%in%`)
```


Check DiscreteWQ
```{r}
# import current discretewq and old discretewq (grabbed from commit 7a6d6a0)
df_new_dwq <- discretewq::wq(Sources = c('EMP'))

load(file='checks/old_emp.rda')

# also check discretewq package version
packageVersion('discretewq')
```

```{r}
# colnames seem fine, difs due to directly importing old EMP data
print(colnames(df_new_dwq)[colnames(df_new_dwq) %ni% colnames(EMP)])
print(colnames(EMP)[colnames(EMP) %ni% colnames(df_new_dwq)])

# removing dif cols for checks
df_new_dwq <- select(df_new_dwq, -c('MonthYear','Year','StationID','Month','Season','Salinity','Salinity_bottom'))
```

```{r}
# everythings okay with discretewq, so going to go forward using new discretewq
all.equal(df_new_dwq, EMP)
```

Check EDI File
```{r}
df_new_edi <- read_csv('checks/Delta_Integrated_WQ.csv')
df_new_edi <- df_new_edi %>% filter(Source == 'EMP')
```

```{r}
# not sure why col names are dif, but shouldn't be causing these issues, so removing for now
print(colnames(df_new_dwq)[colnames(df_new_dwq) %ni% colnames(df_new_edi)])
print(colnames(df_new_edi)[colnames(df_new_edi) %ni% colnames(df_new_dwq)])

# removing dif cols for checks
df_new_edi <- select(df_new_edi, -c('Sample_depth_surface', 'Sample_depth_nutr_surface', 'Sample_depth_bottom', 'Salinity', 'Salinity_bottom', 'Secchi_estimated','Chlorophyll_Sign'))

# order cols so theyre the same for checking purposes
df_new_edi <- df_new_edi %>% select(order(colnames(df_new_edi)))
df_new_dwq <- df_new_dwq %>% select(order(colnames(df_new_dwq)))
```

```{r}
# only big issue is station name, which makes sense, since edi has "EMP" in the station names
# some date issues though? might be relevant? for now ignoring
all.equal(df_new_dwq, df_new_edi)
```

Check Code (new discretewq vs EDI)
```{r}
# slightly modified function so we can import the data ourselves
read_wq_data_mod <- function(df, monthly = TRUE) {
  # temp corrections
  df_time <-readr::read_csv('data/data_in/Time_correction_PST.csv')
  df_time <- dplyr::rename(df_time, Time = Time_PST)

  df <- df %>%
    mutate(Time = round(as.integer(as.numeric(hms::as_hms(Datetime))), -1)) %>%
    left_join(df_time, by = c('Time', 'Month')) %>%
    mutate(Temperature = round(Temperature + Correction,2))

  # if monthly, subset by when zoop starts
  if(monthly){
    df <- subset(df, Date >= '1995-01-01')
  }

  return(df)
}
```

```{r}
# add month cols (orig existed for dwq but not edi for some reason?)
df_new_dwq$Month <- month(df_new_dwq$Datetime)
df_new_edi$Month <- month(df_new_edi$Datetime)
```

```{r}
df_func_dwq <- read_wq_data_mod(df_new_dwq)
df_func_edi <- read_wq_data_mod(df_new_edi)

# issues seem to be the same as before, ie, not relevant. so this section of code is probs fine. nor sure why problem isn't replicating.
all.equal(df_func_dwq, df_func_edi)
```

