---
title: "Make Definations Table"
author: "Peter Dudley"
date: "4/29/2022"
output: html_document
editor_options: 
  chunk_output_type: console
knit: (function(input, ...) {
    
   
    rmarkdown::render(
      input,
      output_dir = 'docs',
      knit_root_dir = "../",
      envir = globalenv()
      )
       })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# Read in the 2 CSVs
```{r packages, message=FALSE, warning=FALSE}
month_defs = read.csv("fig_output/month definitions tabel.csv")

year_defs = read.csv("fig_output/definitions tabel.csv")

full_tabel = month_defs %>% 
  full_join(year_defs, by = c("Variable", "Defination"))

col_order = c("Variable", "Months_missing", "Years_missing", "Defination")
full_tabel_ordered = full_tabel[, col_order]

# Do a little formating of the table
knitr::kable(full_tabel_ordered, col.names = c("Variable",
                                             "Years (missing months)",
                                             "Years (missing years)",
                                             "Defination"))

# Write it as a csv
write.csv(full_tabel_ordered,
          "fig_output/full definitions tabel.csv",
          row.names = FALSE)
```

