---
title: "Preliminary GP models 1"
author: "Tanya Rogers"
date: "10/31/2021"
output: html_document
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = '../docs',
      knit_root_dir = '..',
      envir = globalenv()
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(GPEDM) #devtools::install_github("tanyalrogers/GPEDM")
```

### Import data

```{r dataprep}
combined=read.csv("data/annual_averages/annual_data_compiled.csv")
cnames=read.csv("analysis/column_names.csv", stringsAsFactors = F)
dsub=filter(combined, Year>=1975)
focaldata=dsub[,cnames$Datacolumn]
fvars=cnames$Shortname
colnames(focaldata)=fvars
```

### Derived variables

```{r}
focaldata = focaldata %>% 
  mutate(hzoop=hcope+clad+cyclo) #biomass, herbivorous zooplankton
fvars=c(fvars,"hzoop")
```

### Diagnostic plots and data prep

Histograms, log transform, scale

```{r histo}
#log transform
logvars=fvars[c(cnames$Log=="yes",T)]
logtrans=function(x) {
  x2=x[which(!is.na(x))]
  if(any(x2==0)) {log(x+min(x2[which(x2>0)],na.rm=T))}
  else {log(x)}
}
focaldatalog = focaldata %>% 
  mutate_at(logvars,logtrans)

#scale data
fd=focaldatalog
fd=fd %>% mutate_at(2:length(fvars),scale) %>% 
  mutate_at(2:length(fvars),list("1"=lag))
```

Time series

```{r timeseries, fig.width=8, fig.height=9}

#original units
par(mfrow=c(5,5),mar=c(2,2,3,1))
for(i in 2:length(fvars)) {
  plot.default(x=focaldata[,1],y=focaldata[,i],main=fvars[i], type="o",cex=0.5)
}

#log scaled
par(mfrow=c(5,5),mar=c(2,2,3,1))
for(i in 2:length(fvars)) {
  plot.default(x=fd[,1],y=fd[,i],main=fvars[i], type="o",cex=0.5)
}
```

Bivariate plots

```{r bivariate, fig.width=8, fig.height=8}
psych::pairs.panels(select(fd, year, flow, temp, secchi, chla, hzoop, pcal, mysid, smelt),lm = T)
```

### GP model

```{r}
gp1=fitGP(data=fd,yd="smelt",xd=c("smelt_1","mysid_1","pcal_1","hcope_1","chla_1","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp1)

gp2=fitGP(data=fd,yd="mysid",xd=c("smelt_1","mysid_1","pcal_1","hcope_1","chla_1","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp2)

gp3=fitGP(data=fd,yd="pcal",xd=c("smelt_1","mysid_1","pcal_1","hcope_1","chla_1","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp3)

gp4=fitGP(data=fd,yd="hcope",xd=c("smelt_1","mysid_1","pcal_1","hcope_1","chla_1","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp4)

gp5=fitGP(data=fd,yd="chla",xd=c("smelt_1","mysid_1","pcal_1","hcope_1","chla_1","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp5)

ls=rbind(gp1$pars[1:9],gp2$pars[1:9],gp3$pars[1:9],gp4$pars[1:9],gp5$pars[1:9])
colnames(ls)=gp1$inputs$xd_names[1:9]
rownames(ls)=c("smelt","mysid","pcal","hcope","chla")
ls[which(ls<1E-16)]=NA
corrplot::corrplot(ls, method="color", tl.col = "black", is.cor=F,mar = c(0,0,0,0), na.label = "0",outline = T)

```

Plotting functions

```{r plotting_functions}
getcon_ggplot=function(model) {
  con=getconditionals(model,plot=F)
  npreds=length(grep("_yMean",colnames(con)))
  conlong1=gather(con[,1:(npreds+1)],x,xValue,2:(npreds+1))
  conlong2=gather(con[,c(1,(npreds+2):(2*npreds+1))],ym,yMean,2:(npreds+1))
  conlong3=gather(con[,c(1,(2*npreds+2):(3*npreds+1))],ys,ySD,2:(npreds+1))
  conlong=cbind.data.frame(conlong1,yMean=conlong2$yMean,ySD=conlong3$ySD)
  conlong$x=factor(conlong$x, level=unique(conlong$x))
  ggplot(conlong,aes(x=xValue,y=yMean)) +
    facet_wrap(.~x, scales = "free_x") +
    geom_line() + geom_ribbon(aes(ymin=yMean-ySD,ymax=yMean+ySD), alpha=0.4) +
    theme_bw() +
    labs(y=model$inputs$yd_names, x="Value")
}

pred_ggplot=function(model) {
  ggplot(model$insampresults,aes(x=timestep,y=predmean)) +
    geom_line() + 
    geom_ribbon(aes(ymin=predmean-predfsd,ymax=predmean+predfsd), alpha=0.4) +
    geom_ribbon(aes(ymin=predmean-predsd,ymax=predmean+predsd), alpha=0.4) +
    geom_point(aes(y=obs)) +
    theme_bw() +
    labs(y=model$inputs$yd_names, x="year")
}

```

Predictions (leave-one-out) and conditional responses

```{r}
pred_ggplot(gp1)
getcon_ggplot(gp1)
pred_ggplot(gp2)
getcon_ggplot(gp2)
pred_ggplot(gp3)
getcon_ggplot(gp3)
pred_ggplot(gp4)
getcon_ggplot(gp4)
pred_ggplot(gp5)
getcon_ggplot(gp5)
```

### GP model without time lags

```{r}
gp1=fitGP(data=fd,yd="smelt",xd=c("smelt_1","mysid","pcal","hcope","chla","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp1)

gp2=fitGP(data=fd,yd="mysid",xd=c("smelt","mysid_1","pcal","hcope","chla","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp2)

gp3=fitGP(data=fd,yd="pcal",xd=c("smelt","mysid","pcal_1","hcope","chla","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp3)

gp4=fitGP(data=fd,yd="hcope",xd=c("smelt","mysid","pcal","hcope_1","chla","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp4)

gp5=fitGP(data=fd,yd="chla",xd=c("smelt","mysid","pcal","hcope","chla_1","secchi", "flow","temp","year"),time = "year",predictmethod = "loo")
summary(gp5)

ls=rbind(gp1$pars[1:9],gp2$pars[1:9],gp3$pars[1:9],gp4$pars[1:9],gp5$pars[1:9])
colnames(ls)=gp1$inputs$xd_names[1:9]
rownames(ls)=c("smelt","mysid","pcal","hcope","chla")
ls[which(ls<1E-16)]=NA
corrplot::corrplot(ls, method="color", tl.col = "black", is.cor=F,mar = c(0,0,0,0), na.label = "0",outline = T)

```

Plotting functions

```{r plottingfunctions}
getcon_ggplot=function(model) {
  con=getconditionals(model,plot=F)
  npreds=length(grep("_yMean",colnames(con)))
  conlong1=gather(con[,1:(npreds+1)],x,xValue,2:(npreds+1))
  conlong2=gather(con[,c(1,(npreds+2):(2*npreds+1))],ym,yMean,2:(npreds+1))
  conlong3=gather(con[,c(1,(2*npreds+2):(3*npreds+1))],ys,ySD,2:(npreds+1))
  conlong=cbind.data.frame(conlong1,yMean=conlong2$yMean,ySD=conlong3$ySD)
  conlong$x=factor(conlong$x, level=unique(conlong$x))
  ggplot(conlong,aes(x=xValue,y=yMean)) +
    facet_wrap(.~x, scales = "free_x") +
    geom_line() + geom_ribbon(aes(ymin=yMean-ySD,ymax=yMean+ySD), alpha=0.4) +
    theme_bw() +
    labs(y=model$inputs$yd_names, x="Value")
}

pred_ggplot=function(model) {
  ggplot(model$insampresults,aes(x=timestep,y=predmean)) +
    geom_line() + 
    geom_ribbon(aes(ymin=predmean-predfsd,ymax=predmean+predfsd), alpha=0.4) +
    geom_ribbon(aes(ymin=predmean-predsd,ymax=predmean+predsd), alpha=0.4) +
    geom_point(aes(y=obs)) +
    theme_bw() +
    labs(y=model$inputs$yd_names, x="year")
}

```

Predictions (leave-one-out) and conditional responses

```{r}
pred_ggplot(gp1)
getcon_ggplot(gp1)
pred_ggplot(gp2)
getcon_ggplot(gp2)
pred_ggplot(gp3)
getcon_ggplot(gp3)
pred_ggplot(gp4)
getcon_ggplot(gp4)
pred_ggplot(gp5)
getcon_ggplot(gp5)
```

