---
title: "Annual model - No Regions"
author: "Tanya Rogers"
date: "12/15/2021"
output: html_document
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = '../docs',
      knit_root_dir = '..',
      envir = globalenv()
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE}
library(dplyr)
#library(psych) #for pairs.panels, but could use other packages, e.g. GGalley
library(lavaan)
library(semPlot)
library(DiagrammeR)
library(tidyr)
library(ggplot2)
library(performance)
library(purrr)
```

### Import data

```{r dataprep}
combined=read.csv("data/annual_averages/annual_data_compiled_noregions.csv")
cnames=read.csv("analysis/column_names.csv", stringsAsFactors = F)
dsub=filter(combined, Year>=1975)
focaldata=dsub[,cnames$Datacolumn]
fvars=cnames$Shortname
colnames(focaldata)=fvars

#focal variables
varnames=c("temp","flow","nitrate","ammonia","dophos","chla","hcope","clad","amphi","pcope","mysid","potam","corbic","sside","estfish","estfish_bsot","estfish_bsmt","estfish_stn")

source("analysis/myLavaanPlot.r")
```

### Data prep

Log transform, scale

```{r prep}
#log transform
logvars=fvars[cnames$Log=="yes"]
logtrans=function(x) {
  x2=x[which(!is.na(x))]
  if(any(x2==0)) {log(x+min(x2[which(x2>0)],na.rm=T))}
  else {log(x)}
}
focaldatalog = focaldata %>% 
  mutate_at(logvars,logtrans)

#scale data
fd0=focaldatalog
tvars=fvars[-1]

fd=fd0 %>% 
  #lag
  mutate_at(tvars,list("1"=lag)) %>% 
  #scale
  mutate_at(-1,scale) %>% 
  as.data.frame()

#detrended
fd_dtr=fd0 %>% 
  mutate_at(tvars,function(x) { #detrend
    x2=x
    x2[x2==0]=NA
    res=residuals(lm(x2~fd$year))
    out=x
    out[which(!is.na(x2))]=res
    return(out)
  }) %>%
  #lag
  mutate_at(tvars,list("1"=lag)) %>% 
  #scale
  mutate_at(-1,scale)  %>% 
  as.data.frame()
```

### Time series plots

```{r timeseries, fig.width=8, fig.height=8, echo=FALSE, warning=FALSE}
plot1=select(focaldata,year,varnames) %>% 
  gather(Var,Value,varnames) %>% 
  mutate(Var=factor(Var,levels = varnames))
ggplot(plot1,aes(x=year,y=Value)) +
  facet_wrap(Var~., scales="free_y",ncol = 4) +
  geom_line() +
  theme_bw() +
  labs(title = "Original Units")

plot2=select(fd,year,varnames) %>% 
  gather(Var,Value,varnames) %>% 
  mutate(Var=factor(Var,levels = varnames))
ggplot(plot2,aes(x=year,y=Value)) +
  facet_wrap(Var~.,ncol = 4) +
  geom_line() +
  theme_bw() +
  labs(title = "Log scaled within region")

plot3=select(fd_dtr,year,varnames) %>% 
  gather(Var,Value,varnames) %>% 
  mutate(Var=factor(Var,levels = varnames))
ggplot(plot3,aes(x=year,y=Value)) +
  facet_wrap(Var~.,ncol = 4) +
  geom_line() +
  theme_bw() +
  labs(title = "Log scaled detrended")
```

### Cross-correlation matrices  
(only sig correlations shown... no correction for multiple comparisons)

```{r cc, fig.width=7, fig.height=6, echo=FALSE}
#lag 0
lags0=expand.grid(V1=varnames,V2=varnames,Cor=NA,P=NA,
                  stringsAsFactors = F)
for(i in 1:nrow(lags0)) {
  v1=fd[,lags0$V1[i]]
  v2=fd[,lags0$V2[i]]
  if(!all(is.na(v1)) & !all(is.na(v2))) {
    tccf=cor.test(v1,v2)
    lags0$Cor[i]=tccf$estimate
    lags0$P[i]=tccf$p.value
  }
}
lags0$V1=factor(lags0$V1,levels = varnames)
lags0$V2=factor(lags0$V2,levels = varnames)
ggplot(filter(lags0,P<0.05,V1!=V2), aes(x=V2,y=V1,fill=Cor)) +
  geom_tile() +
  geom_abline(slope=1,intercept = 0) +
  scale_fill_gradient2() +
  theme_bw() +
  labs(x="V2 (t)", y="V1 (t)", title = "lag 0 cross-cor") +
  scale_x_discrete(expand = expand_scale(mult = 0),drop=F) +
  scale_y_discrete(expand = expand_scale(mult = 0),drop=F) +
  theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1))

#lag 1
lags1=expand.grid(V1=varnames,V2=varnames,Cor=NA,P=NA,
                  stringsAsFactors = F)
for(i in 1:nrow(lags1)) {
  v1=fd[,lags1$V1[i]]
  v2=fd[,lags1$V2[i]]
  if(!all(is.na(v1)) & !all(is.na(v2))) {
    tccf=cor.test(v1,lag(v2,1))
    lags1$Cor[i]=tccf$estimate
    lags1$P[i]=tccf$p.value
  }
}
lags1$V1=factor(lags1$V1,levels = varnames)
lags1$V2=factor(lags1$V2,levels = varnames)
ggplot(filter(lags1,P<0.05,V1!=V2), aes(x=V2,y=V1,fill=Cor)) +
  geom_tile() +
  geom_abline(slope=1,intercept = 0) +
  scale_fill_gradient2() +
  theme_bw() +
  labs(x="V2 (t-1)", y="V1 (t)", title = "lag 1 cross-cor") +
  scale_x_discrete(expand = expand_scale(mult = 0),drop=F) +
  scale_y_discrete(expand = expand_scale(mult = 0),drop=F) +
  theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1))

#lag 1 seasonality removed
lags1dtr=expand.grid(V1=varnames,V2=varnames,Cor=NA,P=NA,
                  stringsAsFactors = F)
for(i in 1:nrow(lags1dtr)) {
  v1=fd_dtr[,lags1dtr$V1[i]]
  v2=fd_dtr[,lags1dtr$V2[i]]
  if(!all(is.na(v1)) & !all(is.na(v2))) {
    tccf=cor.test(v1,v2)
    lags1dtr$Cor[i]=tccf$estimate
    lags1dtr$P[i]=tccf$p.value
  }
}
lags1dtr$V1=factor(lags1dtr$V1,levels = varnames)
lags1dtr$V2=factor(lags1dtr$V2,levels = varnames)
ggplot(filter(lags1dtr,P<0.05,V1!=V2), aes(x=V2,y=V1,fill=Cor)) +
  geom_tile() +
  geom_abline(slope=1,intercept = 0) +
  scale_fill_gradient2() +
  theme_bw() +
  labs(x="V2 (t-1)", y="V1 (t)",title = "lag 0 cross-cor, detrended") +
  scale_x_discrete(expand = expand_scale(mult = 0),drop=F) +
  scale_y_discrete(expand = expand_scale(mult = 0),drop=F) +
  theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1))
```

```{r bivariate, fig.width=9, fig.height=9, echo=FALSE, eval=FALSE}
psych::pairs.panels(dplyr::select(fd, year, varnames),lm = T)
```

### SEM model

With and without detrending.

```{r}
fd = fd %>% 
  mutate(rep_zoop_c = hcope_c+clad_c+mysid_c,
         rep_zoop_m = hcope+clad+mysid,
         rep_zoop_e = hcope_e+clad_e+mysid_e,
         all_zoop_c = hcope_c+clad_c+mysid_c+pcope_c+rotif_c,
         all_zoop_m = hcope+clad+mysid+pcope+rotif_m,
         all_zoop_e = hcope_e+clad_e+mysid_e+pcope_e+rotif_e,
         all_fish = estfish_bsmt+estfish_bsot)
  
fd_dtr = fd_dtr %>% 
  mutate(rep_zoop_c = hcope_c+clad_c+mysid_c,
         rep_zoop_m = hcope+clad+mysid,
         rep_zoop_e = hcope_e+clad_e+mysid_e,
         all_zoop_c = hcope_c+clad_c+mysid_c+pcope_c+rotif_c,
         all_zoop_m = hcope+clad+mysid+pcope+rotif_m,
         all_zoop_e = hcope_e+clad_e+mysid_e+pcope_e+rotif_e,
         all_fish = estfish_bsmt+estfish_bsot)
```

```{r}



l_models = data.frame(l_model = c("rep_zoop_c",
                                "rep_zoop_m",
                                "rep_zoop_e",
                                "all_zoop_c",
                                "all_zoop_m",
                                "all_zoop_e",
                                "hcope_c+clad_c+mysid_c",
                                "hcope+clad+mysid",
                                "hcope_e+clad_e+mysid_e",
                                "hcope_c+clad_c+mysid_c+pcope_c+rotif_c",
                                "hcope+clad+mysid+pcope+rotif_m",
                                "hcope_e+clad_e+mysid_e+pcope_e+rotif_e",
                                "amphi+hcope_c+clad_c+mysid_c",
                                "amphi+hcope+clad+mysid",
                                "amphi+hcope_e+clad_e+mysid_e",
                                "amphi+hcope_c+clad_c+mysid_c+pcope_c+rotif_c",
                                "amphi+hcope+clad+mysid+pcope+rotif_m",
                                "amphi+hcope_e+clad_e+mysid_e+pcope_e+rotif_e"),
                      model_name = c("model_r_c",
                                      "model_r_m",
                                      "model_r_e",
                                      "model_a_c",
                                      "model_a_m",
                                      "model_a_e",
                                      "model_l_c",
                                      "model_l_m",
                                      "model_l_e",
                                      "model_al_c",
                                      "model_al_m",
                                      "model_al_e",
                                      "model_la_c",
                                      "model_la_m",
                                      "model_la_e",
                                      "model_ala_c",
                                      "model_ala_m",
                                      "model_ala_e"))



model_list = c(model_l_c = model_l_c,
               model_l_m = model_l_m,
               model_l_e = model_l_e,
               model_la_c = model_la_c,
               model_la_m = model_la_m,
               model_la_e = model_la_e,
               model_r_c = model_r_c,
               model_r_m = model_r_m,
               model_r_e = model_r_e,
               model_a_c = model_a_c,
               model_a_m = model_a_m,
               model_a_e = model_a_e,
               model_al_c = model_al_c,
               model_al_m = model_al_m,
               model_al_e = model_al_e,
               model_ala_c = model_ala_c,
               model_ala_m = model_ala_m,
               model_ala_e = model_ala_e)

AICs_dtr = map(l_models$l_model, ~AIC(lm(paste0("all_fish ~", .x), data = fd_dtr))) %>% 
  unlist() %>% 
  data.frame() %>% 
  setNames("lm_AIC") %>% 
  bind_cols(l_models) %>% 
  mutate(delta_AIC = lm_AIC - min(lm_AIC),
         type = "result_dt")
AICs = map(l_models$l_model, ~AIC(lm(paste0("all_fish ~", .x), data = fd))) %>% 
  unlist() %>% 
  data.frame() %>% 
  setNames("lm_AIC") %>% 
  bind_cols(l_models) %>% 
  mutate(delta_AIC = lm_AIC - min(lm_AIC),
         type = "result") %>% 
  bind_rows(AICs_dtr)
  


```


```{r}
model_l_c='zoop=~hcope_c+clad_c+mysid_c
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_l_m='zoop=~hcope+clad+mysid
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_l_e='zoop=~hcope_e+clad_e+mysid_e
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_la_c='zoop=~hcope_c+clad_c+mysid_c+amphi
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_la_m='zoop=~hcope+clad+mysid+amphi
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_la_e='zoop=~hcope_e+clad_e+mysid_e+amphi
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_r_c='fish=~estfish_bsmt+estfish_bsot
        rep_zoop_c~chla+potam+flow
        chla~potam+flow
        fish~rep_zoop_c+flow'

model_r_m='fish=~estfish_bsmt+estfish_bsot
        rep_zoop_m~chla+potam+flow
        chla~potam+flow
        fish~rep_zoop_m+flow'

model_r_e='fish=~estfish_bsmt+estfish_bsot
        rep_zoop_e~chla+potam+flow
        chla~potam+flow
        fish~rep_zoop_e+flow'

model_a_c='fish=~estfish_bsmt+estfish_bsot
        all_zoop_c~chla+potam+flow
        chla~potam+flow
        fish~all_zoop_c+flow'

model_a_m='fish=~estfish_bsmt+estfish_bsot
        all_zoop_m~chla+potam+flow
        chla~potam+flow
        fish~all_zoop_m+flow'

model_a_e='fish=~estfish_bsmt+estfish_bsot
        all_zoop_e~chla+potam+flow
        chla~potam+flow
        fish~all_zoop_e+flow'

model_al_c='zoop=~hcope_c+clad_c+mysid_c+pcope_c+rotif_c
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_al_m='zoop=~hcope+clad+mysid+pcope+rotif_m
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_al_e='zoop=~hcope_e+clad_e+mysid_e+pcope_e+rotif_e
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_ala_c='zoop=~hcope_c+clad_c+mysid_c+pcope_c+rotif_c+amphi
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_ala_m='zoop=~hcope+clad+mysid+pcope+rotif_m+amphi
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_ala_e='zoop=~hcope_e+clad_e+mysid_e+pcope_e+rotif_e+amphi
        fish=~estfish_bsmt+estfish_bsot
        zoop~chla+potam+flow
        chla~potam+flow
        fish~zoop+flow'

model_list = c(model_l_c = model_l_c,
               model_l_m = model_l_m,
               model_l_e = model_l_e,
               model_la_c = model_la_c,
               model_la_m = model_la_m,
               model_la_e = model_la_e,
               model_r_c = model_r_c,
               model_r_m = model_r_m,
               model_r_e = model_r_e,
               model_a_c = model_a_c,
               model_a_m = model_a_m,
               model_a_e = model_a_e,
               model_al_c = model_al_c,
               model_al_m = model_al_m,
               model_al_e = model_al_e,
               model_ala_c = model_ala_c,
               model_ala_m = model_ala_m,
               model_ala_e = model_ala_e)

```

Plot the IFIs
```{r}

metric = "AIC"
models = data.frame(model_name = names(model_list),
                    models = model_list) %>% 
  rowwise() %>% 
  mutate(result = model_performance(
    sem(models, data = fd),
    metrics = c(metric))[[1]],
    result_dt = model_performance(
      sem(models, data = fd_dtr),
      metrics = c(metric))[[1]]) %>% 
  pivot_longer(cols = c(result, result_dt), names_to = "type", values_to = "metr") %>% 
  mutate(model_name = forcats::fct_reorder(model_name, metr)) %>% 
  left_join(AICs, by = c("model_name", "type"))

IFI_compare = ggplot(data = models,
                     aes(x = lm_AIC,
                         y = metr,
                         color = type)) +
  theme_classic(base_size = 20) +
  labs(y = metric)+
  theme(axis.text.x = element_text(angle = 90)) +
  geom_point()
print(IFI_compare)
```


```{r}

modfit_l_m=sem(model_l_m, data=fd)
modfit_l_m_dtr=sem(model_l_m, data=fd_dtr)

modfit_l_c=sem(model_l_c, data=fd)
modfit_l_c_dtr=sem(model_l_c, data=fd_dtr)

modfit_l_e=sem(model_l_e, data=fd)
modfit_l_e_dtr=sem(model_l_e, data=fd_dtr)

modfit_la_m=sem(model_la_m, data=fd)
modfit_la_m_dtr=sem(model_la_m, data=fd_dtr)

modfit_la_c=sem(model_la_c, data=fd)
modfit_la_c_dtr=sem(model_la_c, data=fd_dtr)

modfit_la_e=sem(model_la_e, data=fd)
modfit_la_e_dtr=sem(model_la_e, data=fd_dtr)

modfit_r_m=sem(model_r_m, data=fd)
modfit_r_m_dtr=sem(model_r_m, data=fd_dtr)

modfit_r_c=sem(model_r_c, data=fd)
modfit_r_c_dtr=sem(model_r_c, data=fd_dtr)

modfit_r_e=sem(model_r_e, data=fd)
modfit_r_e_dtr=sem(model_r_e, data=fd_dtr)

modfit_a_m=sem(model_a_m, data=fd)
modfit_a_m_dtr=sem(model_a_m, data=fd_dtr)

modfit_a_c=sem(model_a_c, data=fd)
modfit_a_c_dtr=sem(model_a_c, data=fd_dtr)

modfit_a_e=sem(model_a_e, data=fd)
modfit_a_e_dtr=sem(model_a_e, data=fd_dtr)

modfit_al_m=sem(model_al_m, data=fd)
modfit_al_m_dtr=sem(model_al_m, data=fd_dtr)

modfit_al_c=sem(model_al_c, data=fd)
modfit_al_c_dtr=sem(model_al_c, data=fd_dtr)

modfit_al_e=sem(model_al_e, data=fd)
modfit_al_e_dtr=sem(model_al_e, data=fd_dtr)

modfit_ala_m=sem(model_ala_m, data=fd)
modfit_ala_m_dtr=sem(model_ala_m, data=fd_dtr)

modfit_ala_c=sem(model_ala_c, data=fd)
modfit_ala_c_dtr=sem(model_ala_c, data=fd_dtr)

modfit_ala_e=sem(model_ala_e, data=fd)
modfit_ala_e_dtr=sem(model_ala_e, data=fd_dtr)

```

### Nice plots

#### Without covariances
Plots

```{r, echo=FALSE}
myLavaanPlot(model=modfit_r_c, 
						 node_options=list(shape="box", fontname="Helvetica"), 
						 coefs=TRUE, stand=TRUE, covs=FALSE, sig=0.05, 
						 width=c("regress","latent"),
						 color=c("regress","latent"))

myLavaanPlot(model=modfit_r_e, 
						 node_options=list(shape="box", fontname="Helvetica"), 
						 coefs=TRUE, stand=TRUE, covs=FALSE, sig=0.05, 
						 width=c("regress","latent"),
						 color=c("regress","latent"))
```

Original units

```{r, echo=FALSE}
myLavaanPlot(model=modfit_m, labels=labels_m,
						 node_options=list(shape="box", fontname="Helvetica"), 
						 coefs=TRUE, stand=TRUE, covs=FALSE, sig=0.05, 
						 width=c("regress","latent"),
						 color=c("regress","latent"))
```

Detrended

```{r, echo=FALSE}
myLavaanPlot(model=modfit1_dtr, labels=labels1, 
						 node_options=list(shape="box", fontname="Helvetica"), 
						 coefs=TRUE, stand=TRUE, covs=FALSE, sig=0.05, 
						 width=c("regress","latent"),
						 color=c("regress","latent"))
```

#### With covariances

Original units

```{r, echo=FALSE}
myLavaanPlot(model=modfit1, labels=labels1, 
						 node_options=list(shape="box", fontname="Helvetica"), 
						 coefs=TRUE, stand=TRUE, covs=TRUE, sig=0.05, 
						 width=c("regress","latent","covs"),
						 color=c("regress","latent","covs"))

```

Detrended

```{r, echo=FALSE}
myLavaanPlot(model=modfit1_dtr, labels=labels1, 
						 node_options=list(shape="box", fontname="Helvetica"), 
						 coefs=TRUE, stand=TRUE, covs=TRUE, sig=0.05, 
						 width=c("regress","latent","covs"),
						 color=c("regress","latent","covs"))
```
